// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhsRQR0KSoB3Ib4B3AIWk4w4qMrRNjRtk',
    appId: '1:974852394687:web:030a1c4982bf400220800a',
    messagingSenderId: '974852394687',
    projectId: 'graduation-project-f8219',
    authDomain: 'graduation-project-f8219.firebaseapp.com',
    storageBucket: 'graduation-project-f8219.firebasestorage.app',
    measurementId: 'G-HMV1RLLQY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIeQ_z6v6tSTvpt-12WLCoizIuKG8QMNs',
    appId: '1:974852394687:android:3017911dd641184420800a',
    messagingSenderId: '974852394687',
    projectId: 'graduation-project-f8219',
    storageBucket: 'graduation-project-f8219.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyoGKFJtt5HJ0PMEp1Zi2FTVCZiNHO2ls',
    appId: '1:974852394687:ios:a0a9a5162df2715120800a',
    messagingSenderId: '974852394687',
    projectId: 'graduation-project-f8219',
    storageBucket: 'graduation-project-f8219.firebasestorage.app',
    iosBundleId: 'com.example.g3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyoGKFJtt5HJ0PMEp1Zi2FTVCZiNHO2ls',
    appId: '1:974852394687:ios:a0a9a5162df2715120800a',
    messagingSenderId: '974852394687',
    projectId: 'graduation-project-f8219',
    storageBucket: 'graduation-project-f8219.firebasestorage.app',
    iosBundleId: 'com.example.g3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhsRQR0KSoB3Ib4B3AIWk4w4qMrRNjRtk',
    appId: '1:974852394687:web:518fd69ba7225a7820800a',
    messagingSenderId: '974852394687',
    projectId: 'graduation-project-f8219',
    authDomain: 'graduation-project-f8219.firebaseapp.com',
    storageBucket: 'graduation-project-f8219.firebasestorage.app',
    measurementId: 'G-TM18TVSVSH',
  );

}